### ISSUE TITLE
camera version is very old

### ISSUE THREAD

**Issue by karanSman** [abdelaziz-mahdy/pytorch_lite#78]
Your package using camera version ^0.10.5+2. update this it is very old.

**Comment by abdelaziz-mahdy** [comment]
A pub upgrade should get the latest version that your project can handle no need to update the camera version since ^ allows version updates in minor version 

Latest camera version is 0.11.0

So a pub upgrade in your project is enough

**Comment by karanSman** [comment]
Because pytorch_lite 4.2.5 depends on camera ^0.10.5+2 and no versions of pytorch_lite match >4.2.5 <5.0.0, pytorch_lite ^4.2.5 requires camera ^0.10.5+2.
And because every version of book_scanner from path depends on camera ^0.11.0+1, pytorch_lite ^4.2.5 is incompatible with book_scanner from path.

**Comment by abdelaziz-mahdy** [comment]
You can use dependency overrides for now, when I start working on the package will update it

**Comment by josephmangmang** [comment]
Resolving dependencies...
Because pytorch_lite >=3.0.0-alpha depends on camera ^0.10.5+2 and every version of ocr from path depends on camera ^0.11.0+1, pytorch_lite >=3.0.0-alpha is incompatible with PACKAGE from path.
So, because example depends on ocr from path which depends on pytorch_lite ^4.2.4, version solving failed.

![Screenshot 2024-08-02 at 7 31 50 PM](https://github.com/user-attachments/assets/c172c46a-9e5f-49b0-82f0-1397c64ff3aa)
I tried overriding it but it cannot be overridden

**Comment by abdelaziz-mahdy** [comment]
@josephmangmang don't use the camera version you need in the dependency, just put it in the override

Please share your full pubspec
